# Generated by Django 4.2.3 on 2023-09-18 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.PositiveBigIntegerField()),
                ('adresse', models.TextField()),
            ],
        ),
    ]
