# Generated by Django 4.2.3 on 2023-09-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Blog_bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('contenu', models.CharField(max_length=200)),
                ('date_publication', models.DateTimeField()),
                ('auteur', models.CharField(max_length=50)),
            ],
        ),
    ]
