# Generated by Django 4.2.3 on 2023-09-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_blog_bd',
            name='date_publication',
            field=models.CharField(max_length=50),
        ),
    ]
