# Generated by Django 4.2.3 on 2023-09-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicesmodeles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liste_Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('adresse_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
