# Generated by Django 4.2.3 on 2023-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicesmodeles', '0002_liste_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette_Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_recette', models.CharField(max_length=30)),
                ('ingredients', models.CharField(max_length=200)),
                ('instruc_cooking', models.CharField(max_length=300)),
            ],
        ),
    ]
