# Generated by Django 4.2.3 on 2023-09-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicesmodeles', '0004_user_commentaire_blog_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse_questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
