# Generated by Django 4.2.3 on 2023-09-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicesmodeles', '0005_reponse_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
