# Generated by Django 4.2.3 on 2023-09-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercicesmodeles', '0006_produit_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Produits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=50)),
                ('id_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercicesmodeles.categories_produits')),
            ],
        ),
    ]
