# Generated by Django 4.2.3 on 2023-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicesmodeles', '0008_pays_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('moyenne_notes', models.FloatField()),
            ],
        ),
    ]
