# Generated by Django 4.2.3 on 2023-09-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Repetitifs_test1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
