# Generated by Django 4.2.3 on 2023-09-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0002_etudiant_transactions_financieres'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Taches_afaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField()),
            ],
        ),
    ]
