# Generated by Django 4.2.3 on 2023-09-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0003_my_events_taches_afaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publiee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_account', models.BooleanField()),
            ],
        ),
    ]
