# Generated by Django 4.2.3 on 2023-09-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0004_articles_blog_utilisateurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='code_SKU',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nom',
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Commandes_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commandes', models.CharField(max_length=20)),
                ('id_produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='types_champs_app.produit')),
            ],
        ),
    ]
