# Generated by Django 4.2.3 on 2023-09-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0005_remove_produit_code_sku_remove_produit_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profils_Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_de_profil', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='telecharger_fichiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='')),
            ],
        ),
    ]
