# Generated by Django 4.2.3 on 2023-09-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0009_users_users_groupes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('membres', models.ManyToManyField(to='types_champs_app.invitees')),
            ],
        ),
    ]
