# Generated by Django 4.2.3 on 2023-09-18 22:19

import django.core.validators
from django.db import migrations, models
import types_champs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0010_invitees_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('adresse', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('code_postal', models.CharField(max_length=100, validators=[types_champs_app.models.validate_code_postal])),
            ],
        ),
    ]
