# Generated by Django 4.2.3 on 2023-09-18 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0011_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('budget', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
    ]
