# Generated by Django 4.2.3 on 2023-09-18 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0012_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAvecImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
