# Generated by Django 4.2.3 on 2023-09-18 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0015_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
