# Generated by Django 4.2.3 on 2023-09-18 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0016_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
                ('heure_debut', models.TimeField()),
            ],
        ),
    ]
