# Generated by Django 4.2.3 on 2023-09-18 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0017_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('fichier_audio', models.FileField(upload_to='')),
            ],
        ),
    ]
