# Generated by Django 4.2.3 on 2023-09-18 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_champs_app', '0018_musique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('type_ville', models.CharField(choices=[('PL', 'Plage'), ('Mng', 'Montagne'), ('VL', 'Ville')], max_length=50)),
            ],
        ),
    ]
